name: Busing <-> MQTT bridge (Python)
version: 0.1.0
slug: ingenium_busing_mqtt_py
description: Publish Ingenium/Fermax Events into MQTT (Python rewrite, beta)
url: https://github.com/GermanDZ/home-assistant-addons/tree/main/busing-bridge-py
arch:
  - armhf
  - armv7
  - amd64
  - aarch64
  - i386
startup: services
boot: auto
init: false
stage: experimental
services:
  - mqtt:need
options:
  bridge_enabled: true
  forward_all_events: false
  busing_host: null
  busing_port: 12347
  full_resync_every: 60
  busing_entities: []
  busing_devices_installed: 5
  busing_device_configuration: []
  mqtt_config:
    MQTT_HOST: null
    MQTT_PORT: 1883
    MQTT_SSL: false
    MQTT_USERNAME: null
    MQTT_PASSWORD: null
  mqtt_topic: busing
  log_level: info
schema:
  bridge_enabled: bool?
  forward_all_events: bool?
  busing_host: str
  busing_port: int?
  full_resync_every: int?
  busing_entities:
    - str
  busing_devices_installed: int
  busing_device_configuration:
    - type: str
      outputs:
        - str
      registers:
        - str?
  mqtt_config:
    MQTT_HOST: str
    MQTT_PORT: int?
    MQTT_SSL: bool?
    MQTT_USERNAME: str?
    MQTT_PASSWORD: password?
  mqtt_topic: str
  log_level: list(debug|info|warning|error)?
